import type { NextConfig } from "next";

const isProd = process.env.NODE_ENV === "production";

/**
 * Content-Security-Policy, deployed Report-Only first: violations are POSTed
 * to /api/report (logged server-side) without blocking anything. Promote to
 * the enforcing header once the log stays clean for a few weeks.
 *
 * `'unsafe-inline'` for scripts is deliberate: Next's hydration payload, the
 * theme/consent/a11y bootstraps and the JSON-LD are inline, and nonces would
 * require per-request rendering — which would undo the static generation
 * restored in audit item U1. Hash-pinning the three bootstraps is the next
 * hardening step.
 *
 * When analytics land (audit item U2) add the vendor origins to script-src,
 * connect-src and img-src.
 */
const csp = [
  "default-src 'self'",
  "script-src 'self' 'unsafe-inline'",
  "style-src 'self' 'unsafe-inline'",
  "img-src 'self' data: blob:",
  "font-src 'self' data:",
  "connect-src 'self'",
  "worker-src 'self' blob:",
  "frame-ancestors 'none'",
  "base-uri 'self'",
  "form-action 'self'",
  "object-src 'none'",
  "upgrade-insecure-requests",
  "report-uri /api/report",
].join("; ");

const securityHeaders = [
  // Two years, subdomains, preload-list eligible. Ignored over plain HTTP.
  { key: "Strict-Transport-Security", value: "max-age=63072000; includeSubDomains; preload" },
  { key: "X-Content-Type-Options", value: "nosniff" },
  // The contact form must never be embeddable in a third-party iframe.
  { key: "X-Frame-Options", value: "DENY" },
  { key: "Referrer-Policy", value: "strict-origin-when-cross-origin" },
  {
    key: "Permissions-Policy",
    value: "camera=(), microphone=(), geolocation=(), payment=(), usb=(), browsing-topics=()",
  },
  { key: "X-DNS-Prefetch-Control", value: "on" },
  ...(isProd ? [{ key: "Content-Security-Policy-Report-Only", value: csp }] : []),
];

const nextConfig: NextConfig = {
  reactStrictMode: true,
  // Allow running a second dev server with its own build cache to avoid
  // ".next" lock conflicts (set NEXT_DIST_DIR for the secondary instance).
  ...(process.env.NEXT_DIST_DIR ? { distDir: process.env.NEXT_DIST_DIR } : {}),
  images: {
    // No on-demand optimizer (Vercel meters every transformation): a custom
    // loader serves the variants pre-generated by scripts/build-images.mjs.
    // Keep these width lists in sync with WIDTHS in that script.
    loader: "custom",
    loaderFile: "./src/lib/image-loader.ts",
    deviceSizes: [640, 828, 1080, 1280, 1600, 1920, 2560],
    imageSizes: [48, 96, 192, 384],
    // Some images pass quality 85; the prop must be listed even if the custom
    // loader ignores it.
    qualities: [75, 85],
  },
  async headers() {
    return [{ source: "/(.*)", headers: securityHeaders }];
  },
  // Removed or merged sub-services → the page that now holds their content
  // (public URLs, whose first segment is localized: see i18n/routes.ts).
  async redirects() {
    const moved = [
      // removed: automatisation-ia keeps the offer on its own page
      { from: "automatisation-ia/:child(automatisation-workflows|agents-assistants-ia|ia-contenu-generatif)", to: "automatisation-ia" },
      // merged into "Identité visuelle & charte graphique"
      { from: "branding-design/charte-graphique", to: "branding-design/identite-visuelle" },
      { from: "branding-design/strategie-de-marque-naming", to: "branding-design" },
      { from: "lead-generation/optimisation-conversion-cro", to: "lead-generation" },
    ];
    const locales = [
      ["fr", "services"],
      ["en", "services"],
      ["de", "leistungen"],
      ["es", "servicios"],
    ];
    return moved.flatMap(({ from, to }) =>
      locales.map(([lang, seg]) => ({
        source: `/${lang}/${seg}/${from}`,
        destination: `/${lang}/${seg}/${to}`,
        permanent: true,
      }))
    );
  },
};

export default nextConfig;
