// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/[lang]" | "/[lang]/agence" | "/[lang]/approche" | "/[lang]/confidentialite" | "/[lang]/contact" | "/[lang]/cookies" | "/[lang]/faq" | "/[lang]/glossaire" | "/[lang]/mentions-legales" | "/[lang]/merci" | "/[lang]/news" | "/[lang]/news/[slug]" | "/[lang]/realisations" | "/[lang]/services" | "/[lang]/services/[slug]" | "/[lang]/services/[slug]/[child]" | "/[lang]/style-guide"
type AppRouteHandlerRoutes = "/api/contact"
type PageRoutes = never
type LayoutRoutes = "/[lang]"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/[lang]": { "lang": string; }
  "/[lang]/agence": { "lang": string; }
  "/[lang]/approche": { "lang": string; }
  "/[lang]/confidentialite": { "lang": string; }
  "/[lang]/contact": { "lang": string; }
  "/[lang]/cookies": { "lang": string; }
  "/[lang]/faq": { "lang": string; }
  "/[lang]/glossaire": { "lang": string; }
  "/[lang]/mentions-legales": { "lang": string; }
  "/[lang]/merci": { "lang": string; }
  "/[lang]/news": { "lang": string; }
  "/[lang]/news/[slug]": { "lang": string; "slug": string; }
  "/[lang]/realisations": { "lang": string; }
  "/[lang]/services": { "lang": string; }
  "/[lang]/services/[slug]": { "lang": string; "slug": string; }
  "/[lang]/services/[slug]/[child]": { "lang": string; "slug": string; "child": string; }
  "/[lang]/style-guide": { "lang": string; }
  "/api/contact": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/[lang]": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
