// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../../src/app/[lang]/agence/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[lang]/agence">> = Specific
  const handler = {} as typeof import("../../../src/app/[lang]/agence/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/[lang]/approche/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[lang]/approche">> = Specific
  const handler = {} as typeof import("../../../src/app/[lang]/approche/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/[lang]/confidentialite/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[lang]/confidentialite">> = Specific
  const handler = {} as typeof import("../../../src/app/[lang]/confidentialite/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/[lang]/contact/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[lang]/contact">> = Specific
  const handler = {} as typeof import("../../../src/app/[lang]/contact/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/[lang]/cookies/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[lang]/cookies">> = Specific
  const handler = {} as typeof import("../../../src/app/[lang]/cookies/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/[lang]/faq/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[lang]/faq">> = Specific
  const handler = {} as typeof import("../../../src/app/[lang]/faq/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/[lang]/glossaire/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[lang]/glossaire">> = Specific
  const handler = {} as typeof import("../../../src/app/[lang]/glossaire/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/[lang]/mentions-legales/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[lang]/mentions-legales">> = Specific
  const handler = {} as typeof import("../../../src/app/[lang]/mentions-legales/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/[lang]/merci/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[lang]/merci">> = Specific
  const handler = {} as typeof import("../../../src/app/[lang]/merci/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/[lang]/news/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[lang]/news/[slug]">> = Specific
  const handler = {} as typeof import("../../../src/app/[lang]/news/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/[lang]/news/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[lang]/news">> = Specific
  const handler = {} as typeof import("../../../src/app/[lang]/news/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/[lang]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[lang]">> = Specific
  const handler = {} as typeof import("../../../src/app/[lang]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/[lang]/realisations/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[lang]/realisations">> = Specific
  const handler = {} as typeof import("../../../src/app/[lang]/realisations/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/[lang]/services/[slug]/[child]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[lang]/services/[slug]/[child]">> = Specific
  const handler = {} as typeof import("../../../src/app/[lang]/services/[slug]/[child]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/[lang]/services/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[lang]/services/[slug]">> = Specific
  const handler = {} as typeof import("../../../src/app/[lang]/services/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/[lang]/services/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[lang]/services">> = Specific
  const handler = {} as typeof import("../../../src/app/[lang]/services/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/[lang]/style-guide/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[lang]/style-guide">> = Specific
  const handler = {} as typeof import("../../../src/app/[lang]/style-guide/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/contact/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/contact">> = Specific
  const handler = {} as typeof import("../../../src/app/api/contact/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../../src/app/[lang]/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/[lang]">> = Specific
  const handler = {} as typeof import("../../../src/app/[lang]/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
